-- Step 1: Define regular table
CREATE TABLE IF NOT EXISTS automatica_largoiko (

    time timestamp without time zone default (now( )+ '2 hour'::interval) NOT NULL,
    b_fila_completa_pulmon BOOLEAN NULL,
    b_fila_cinta_evacuacion BOOLEAN NULL,
    b_intermedia_cinta_evacuacion BOOLEAN NULL,
    eje_electrico BOOLEAN NULL,
    ningun_casete_seleccionado BOOLEAN NULL,
    variador_cinta_en_error BOOLEAN NULL,
    seta_emergencia_mod1 BOOLEAN NULL,
    seta_emergencia_mod2 BOOLEAN NULL,
    seta_emergencia_mod3 BOOLEAN NULL,
    barrera_seguridad_1 BOOLEAN NULL,
    barrera_seguridad_2 BOOLEAN NULL,
    puerta_1 BOOLEAN NULL,
    puerta_2 BOOLEAN NULL,
    baliza_amari_mod3 BOOLEAN NULL,
    baliza_rojo_mod3 BOOLEAN NULL,
    baliza_verde_mod3 BOOLEAN NULL,
    baliza1_amari_mod1 BOOLEAN NULL,
    baliza1_rojo_mod1 BOOLEAN NULL,
    baliza1_verde_mod1 BOOLEAN NULL,
    baliza2_amari_mod1 BOOLEAN NULL,
    baliza2_rojo_mod1 BOOLEAN NULL,
    baliza2_verde_mod1 BOOLEAN NULL,
    ev_pinza_1 BOOLEAN NULL,
    ev_pinza_2 BOOLEAN NULL,
    ev_pinza_3 BOOLEAN NULL,
    ev_pinza_4 BOOLEAN NULL,
    ev_pinza_sujeccion_caja_e_cierre BOOLEAN NULL,
    ev_pinza_sujeccion_caja_e_impresora BOOLEAN NULL,
    marcha_variador_cinta BOOLEAN NULL,
    casette_1 BOOLEAN NULL,
    casette_2 BOOLEAN NULL,
    condiciones_iniciales_estacion_1 BOOLEAN NULL,
    estacion_4_ausencia_de_caja BOOLEAN NULL,
    exceso_de_piezas_en_vibrador_1 BOOLEAN NULL,
    exceso_de_piezas_en_vibrador_2 BOOLEAN NULL,
    exceso_de_piezas_en_vibrador_3 BOOLEAN NULL,
    exceso_de_piezas_en_vibrador_4 BOOLEAN NULL,
    sensor_de_parada_alimentador_1 BOOLEAN NULL,
    sensor_de_parada_alimentador_2 BOOLEAN NULL,
    sensor_de_parada_alimentador_3 BOOLEAN NULL,
    sensor_de_parada_alimentador_4 BOOLEAN NULL,
    sensor_de_caja_estacion_4 BOOLEAN NULL,
    condiciones_iniciales_estacion_4 BOOLEAN NULL,
    fin_estacion_4 BOOLEAN NULL,
    permisode_trabajo_estacion_4 BOOLEAN NULL,
    atasco_embudo_vibrador_5 BOOLEAN NULL,
    atasco_embudo_vibrador_6 BOOLEAN NULL,
    atasco_embudo_vibrador_7 BOOLEAN NULL,
    estacion_7_ausencia_de_caja BOOLEAN NULL,
    exceso_de_piezas_en_vibrador_5 BOOLEAN NULL,
    exceso_de_piezas_en_vibrador_6 BOOLEAN NULL,
    exceso_de_piezas_en_vibrador_7 BOOLEAN NULL,
    sensor_de_parada_alimentador_5 BOOLEAN NULL,
    sensor_de_parada_alimentador_6 BOOLEAN NULL,
    sensor_de_parada_alimentador_7 BOOLEAN NULL,
    sensor_de_caja_estacion_7 BOOLEAN NULL,
    condiciones_iniciales_estacion_7 BOOLEAN NULL,
    fin_estacion_7 BOOLEAN NULL,
    permisode_trabajo_estacion_7 BOOLEAN NULL,
    estacion_8_ausencia_de_caja BOOLEAN NULL,
    exceso_de_piezas_en_vibrador_8 BOOLEAN NULL,
    sensor_de_parada_alimentador_8 BOOLEAN NULL,
    sensor_de_caja_estacion_8 BOOLEAN NULL,
    condiciones_iniciales_estacion_8 BOOLEAN NULL,
    fin_estacion_8 BOOLEAN NULL,
    permisode_trabajo_estacion_8 BOOLEAN NULL,
    defecto_de_pieza_estacion_9 BOOLEAN NULL,
    estacion_9_ausencia_de_caja BOOLEAN NULL,
    exceso_de_piezas_vibrador_9 BOOLEAN NULL,
    goma_atascada_en_embudo_vibrador_9 BOOLEAN NULL,
    sensor_de_parada_alimentador_9 BOOLEAN NULL,
    sensor_de_paso_alimentador_9 BOOLEAN NULL,
    sensor_de_caja_estacion_9 BOOLEAN NULL,
    condiciones_iniciales_estacion_9 BOOLEAN NULL,
    fin_estacion_9 BOOLEAN NULL,
    permisode_trabajo_estacion_9 BOOLEAN NULL,
    b_pinza_sujeccion_caja_est_cierre_caja BOOLEAN NULL,
    ausencia_caja_estacion_cierre BOOLEAN NULL,
    condiciones_iniciales_estacion_13 BOOLEAN NULL,
    fin_estacion_13 BOOLEAN NULL,
    permisode_trabajo_estacion_13 BOOLEAN NULL,
    ausencia_de_caja_estacion_14 BOOLEAN NULL,
    condiciones_iniciales_estacion_14 BOOLEAN NULL,
    fin_estacion_14 BOOLEAN NULL,
    permisode_trabajo_estacion_14 BOOLEAN NULL,
    b_pinza_e_etiqueta_t BOOLEAN NULL,
    b_vacuestato_recogida_etiq BOOLEAN NULL,
    condiciones_iniciales_estacion_15 BOOLEAN NULL,
    fin_estacion_15 BOOLEAN NULL,
    permisode_trabajo_estacion_15 BOOLEAN NULL,
    b_presencia_e__extraccion BOOLEAN NULL,
    condiciones_iniciales_estacion_16 BOOLEAN NULL,
    fin_estacion_16 BOOLEAN NULL,
    permisode_trabajo_estacion_16 BOOLEAN NULL,
    alarma_en_estacion_e1 BOOLEAN NULL,
    alarma_en_estacion_e4 BOOLEAN NULL,
    alarma_en_estacion_e7 BOOLEAN NULL,
    alarma_en_estacion_e8 BOOLEAN NULL,
    alarma_en_estacion_e9 BOOLEAN NULL,
    alarma_en_estacion_e13 BOOLEAN NULL,
    alarma_en_estacion_e14 BOOLEAN NULL,
    alarma_en_estacion_e15 BOOLEAN NULL,
    alarma_en_estacion_e16 BOOLEAN NULL,
    receta_nok BOOLEAN NULL,
    fin_estacion_1 BOOLEAN NULL,
    permiso_de_trabajo_estacion_1 BOOLEAN NULL,
    contador_cajas_fila INT NULL,
    cajas_fabricadas INT NULL,
    preseleccion_cajas INT NULL,
    contador_kits_turno INT NULL,
    numero_piezas_vibrador_1 INT NULL,
    activo_vibrador_1 BOOLEAN NULL,
    numero_piezas_vibrador_2 INT NULL,
    activo_vibrador_2 BOOLEAN NULL,
    numero_piezas_vibrador_3 INT NULL,
    activo_vibrador_3 BOOLEAN NULL,
    numero_piezas_vibrador_4 INT NULL,
    activo_vibrador_4 BOOLEAN NULL,
    numero_piezas_vibrador_5 INT NULL,
    activo_vibrador_5 BOOLEAN NULL,
    numero_piezas_vibrador_6 INT NULL,
    activo_vibrador_6 BOOLEAN NULL,
    numero_piezas_vibrador_7 INT NULL,
    activo_vibrador_7 BOOLEAN NULL,
    numero_piezas_vibrador_8 INT NULL,
    activo_vibrador_8 BOOLEAN NULL,
    numero_piezas_vibrador_9 INT NULL,
    activo_vibrador_9 BOOLEAN NULL,
    permiso_de_trabajo_estacion_4_1 BOOLEAN NULL,
    permiso_de_trabajo_estacion_4_2 BOOLEAN NULL,
    permiso_de_trabajo_estacion_4_3 BOOLEAN NULL,
    permiso_de_trabajo_estacion_4_4 BOOLEAN NULL,
    permiso_de_trabajo_estacion_7_1 BOOLEAN NULL,
    permiso_de_trabajo_estacion_7_2 BOOLEAN NULL,
    permiso_de_trabajo_estacion_7_3 BOOLEAN NULL,
    marcha_auto BOOLEAN NULL,
    alarma_general BOOLEAN NULL,
    sensor_caja_estacion_13 BOOLEAN NULL,
    sensor_caja_estacion_14 BOOLEAN NULL,
    sensor_caja_estacion_15 BOOLEAN NULL,
    alarma_ausencia_caja_estacion_15 BOOLEAN NULL,
    alarma_ausencia_caja_estacion_16 BOOLEAN NULL,
    det_pinza_est4 BOOLEAN NULL,
    det_pinza_est7 BOOLEAN NULL,
    det_pinza_est8 BOOLEAN NULL,
    det_pinza_est9 BOOLEAN NULL,
    alarma_error_impresora BOOLEAN NULL,
    alarma_det_cil_impresora_arriba BOOLEAN NULL,
    alarma_barrera1_seguridad_mod_1_nok_cambio_casette BOOLEAN NULL,
    alarma_barrera2_seguridad_mod_1_nok_cambio_casette BOOLEAN NULL,
    nombre_receta VARCHAR,
    nombre_pieza_vibrador_1 VARCHAR,
    nombre_pieza_vibrador_2 VARCHAR,
    nombre_pieza_vibrador_3 VARCHAR,
    nombre_pieza_vibrador_4 VARCHAR,
    nombre_pieza_vibrador_5 VARCHAR,
    nombre_pieza_vibrador_6 VARCHAR,
    nombre_pieza_vibrador_7 VARCHAR,
    nombre_pieza_vibrador_8 VARCHAR,
    nombre_pieza_vibrador_9 VARCHAR

);

-- Step 2: Turn into hypertable
SELECT create_hypertable('automatica_largoiko','time');

-- Model metadata
CREATE TABLE IF NOT EXISTS public.metadata (
	model varchar NOT NULL,
	"timestamp" timestamp NULL,
	sample_size int8 NULL,
	mask_mode varchar NULL,
	mask_lda float8 NULL,
	detect_thresh float8 NULL,
	class_thresh float8 NULL,
	test_acc float8 NULL,
	test_prec float8 NULL,
	test_rec float8 NULL,
	test_f1 float8 NULL,
	test_brier float8 NULL,
	test_roc float8 NULL,
	test_tpr float8 NULL,
	test_fpr float8 NULL,
	test_tnr float8 NULL,
	test_fnr float8 NULL,
	nsamp_total int8 NULL,
	nsamp_positive int8 NULL,
	nsamp_negative int8 NULL,
	nsamp_train int8 NULL,
	nsamp_eval int8 NULL,
	nsamp_test int8 NULL,
	nepochs int8 NULL,
	CONSTRAINT metadata_pk PRIMARY KEY (model)
);

-- ROF predictions
CREATE TABLE IF NOT EXISTS public.predictions (
	ts timestamp NOT NULL,
	rof float8 NOT NULL,
	model varchar NOT NULL
);

-- Forecasting performance
CREATE TABLE IF NOT EXISTS public.fcast_data (
	model varchar NOT NULL,
	shift int4 NOT NULL,
	prob_avg float8 NOT NULL,
	prob_std float8 NOT NULL,
	acc float8 NOT NULL,
	brier float8 NOT NULL
);

-- Training statistics
CREATE TABLE IF NOT EXISTS public.train_data (
	model varchar NOT NULL,
	epoch int4 NOT NULL,
	loss_train float8 NOT NULL,
	loss_eval float8 NOT NULL,
	roc_train float8 NOT NULL,
	roc_eval float8 NOT NULL,
	pr_train float8 NOT NULL,
	pr_eval float8 NOT NULL
);